const level = [
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "X                                                                     X",
    "XXXXXXXXXXXXXXXXXXXXXX                                                X",
    "X                    X                                                X",
    "X                    X                                                X",
    "X                                                                     X",
    "X                M                                                    X",
    "X                X                                                    X",
    "XXXXXXXXXXXXXXXXXXXXXX-                                               X",
    "X                    X                                                X",
    "X                    X   vv                                           X",
    "X                    X                                                X",
    "X                    X                                                X",
    "X      vv  X         X                                                X",
    "X          X                                                          X",
    "X          X     <<>>MMMMMMMMMM                     XX                X",
    "X          X         XXXXXXXXXX---   ---X                             X",
    "X          X         X        X         X     XX                      X",
    "X          X         X        X         X                             X",
    "X  ^^      X         X        X   ---   X                             X",
    "X                       XXXX                                          X",
    "X             R         XXXX                                          X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
];